
namespace CapaPresentacion
{
    partial class frmSubMenu
    {
        /// <summary> 
        /// Variable del diseñador necesaria.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Limpiar los recursos que se estén usando.
        /// </summary>
        /// <param name="disposing">true si los recursos administrados se deben desechar; false en caso contrario.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Código generado por el Diseñador de componentes

        /// <summary> 
        /// Método necesario para admitir el Diseñador. No se puede modificar
        /// el contenido de este método con el editor de código.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmSubMenu));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges13 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges14 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges15 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges16 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges17 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges18 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges19 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges20 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.btnOption1_2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnOption1_1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tabPage3 = new System.Windows.Forms.TabPage();
            this.btnOption2_2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnOption2_1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.btnOption3_3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnOption3_2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnOption3_1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tabPage4 = new System.Windows.Forms.TabPage();
            this.btnOpcion4_2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnOpcion4_1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.hider = new System.Windows.Forms.Panel();
            this.tabPage5 = new System.Windows.Forms.TabPage();
            this.btnOption5_1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tabPage3.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.tabPage4.SuspendLayout();
            this.tabPage5.SuspendLayout();
            this.SuspendLayout();
            // 
            // tabControl1
            // 
            this.tabControl1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPage3);
            this.tabControl1.Controls.Add(this.tabPage2);
            this.tabControl1.Controls.Add(this.tabPage4);
            this.tabControl1.Controls.Add(this.tabPage5);
            this.tabControl1.Location = new System.Drawing.Point(-6, 0);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(234, 708);
            this.tabControl1.TabIndex = 0;
            // 
            // tabPage1
            // 
            this.tabPage1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.tabPage1.Controls.Add(this.btnOption1_2);
            this.tabPage1.Controls.Add(this.btnOption1_1);
            this.tabPage1.Location = new System.Drawing.Point(4, 22);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tabPage1.Size = new System.Drawing.Size(226, 682);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "0";
            // 
            // btnOption1_2
            // 
            this.btnOption1_2.AllowAnimations = false;
            this.btnOption1_2.AllowMouseEffects = true;
            this.btnOption1_2.AllowToggling = true;
            this.btnOption1_2.AnimationSpeed = 200;
            this.btnOption1_2.AutoGenerateColors = false;
            this.btnOption1_2.AutoRoundBorders = false;
            this.btnOption1_2.AutoSizeLeftIcon = true;
            this.btnOption1_2.AutoSizeRightIcon = true;
            this.btnOption1_2.BackColor = System.Drawing.Color.Transparent;
            this.btnOption1_2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption1_2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnOption1_2.BackgroundImage")));
            this.btnOption1_2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption1_2.ButtonText = "Matricular";
            this.btnOption1_2.ButtonTextMarginLeft = 0;
            this.btnOption1_2.ColorContrastOnClick = 45;
            this.btnOption1_2.ColorContrastOnHover = 45;
            this.btnOption1_2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.btnOption1_2.CustomizableEdges = borderEdges11;
            this.btnOption1_2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnOption1_2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOption1_2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOption1_2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOption1_2.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnOption1_2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnOption1_2.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOption1_2.ForeColor = System.Drawing.Color.Gray;
            this.btnOption1_2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOption1_2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnOption1_2.IconLeftPadding = new System.Windows.Forms.Padding(23, 3, 3, 3);
            this.btnOption1_2.IconMarginLeft = 11;
            this.btnOption1_2.IconPadding = 10;
            this.btnOption1_2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOption1_2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnOption1_2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnOption1_2.IconSize = 25;
            this.btnOption1_2.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption1_2.IdleBorderRadius = 1;
            this.btnOption1_2.IdleBorderThickness = 1;
            this.btnOption1_2.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption1_2.IdleIconLeftImage = null;
            this.btnOption1_2.IdleIconRightImage = null;
            this.btnOption1_2.IndicateFocus = true;
            this.btnOption1_2.Location = new System.Drawing.Point(3, 48);
            this.btnOption1_2.Name = "btnOption1_2";
            this.btnOption1_2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOption1_2.OnDisabledState.BorderRadius = 1;
            this.btnOption1_2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption1_2.OnDisabledState.BorderThickness = 1;
            this.btnOption1_2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOption1_2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOption1_2.OnDisabledState.IconLeftImage = null;
            this.btnOption1_2.OnDisabledState.IconRightImage = null;
            this.btnOption1_2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(73)))), ((int)(((byte)(79)))));
            this.btnOption1_2.onHoverState.BorderRadius = 1;
            this.btnOption1_2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption1_2.onHoverState.BorderThickness = 1;
            this.btnOption1_2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(73)))), ((int)(((byte)(79)))));
            this.btnOption1_2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnOption1_2.onHoverState.IconLeftImage = null;
            this.btnOption1_2.onHoverState.IconRightImage = null;
            this.btnOption1_2.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption1_2.OnIdleState.BorderRadius = 1;
            this.btnOption1_2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption1_2.OnIdleState.BorderThickness = 1;
            this.btnOption1_2.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption1_2.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btnOption1_2.OnIdleState.IconLeftImage = null;
            this.btnOption1_2.OnIdleState.IconRightImage = null;
            this.btnOption1_2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(64)))), ((int)(((byte)(69)))));
            this.btnOption1_2.OnPressedState.BorderRadius = 1;
            this.btnOption1_2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption1_2.OnPressedState.BorderThickness = 1;
            this.btnOption1_2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(64)))), ((int)(((byte)(69)))));
            this.btnOption1_2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnOption1_2.OnPressedState.IconLeftImage = null;
            this.btnOption1_2.OnPressedState.IconRightImage = null;
            this.btnOption1_2.Size = new System.Drawing.Size(220, 45);
            this.btnOption1_2.TabIndex = 1;
            this.btnOption1_2.Tag = "0";
            this.btnOption1_2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOption1_2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnOption1_2.TextMarginLeft = 0;
            this.btnOption1_2.TextPadding = new System.Windows.Forms.Padding(25, 0, 0, 0);
            this.btnOption1_2.UseDefaultRadiusAndThickness = true;
            this.btnOption1_2.Click += new System.EventHandler(this.btnOption1_2_Click);
            // 
            // btnOption1_1
            // 
            this.btnOption1_1.AllowAnimations = false;
            this.btnOption1_1.AllowMouseEffects = true;
            this.btnOption1_1.AllowToggling = true;
            this.btnOption1_1.AnimationSpeed = 200;
            this.btnOption1_1.AutoGenerateColors = false;
            this.btnOption1_1.AutoRoundBorders = false;
            this.btnOption1_1.AutoSizeLeftIcon = true;
            this.btnOption1_1.AutoSizeRightIcon = true;
            this.btnOption1_1.BackColor = System.Drawing.Color.Transparent;
            this.btnOption1_1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption1_1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnOption1_1.BackgroundImage")));
            this.btnOption1_1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption1_1.ButtonText = "Text 1";
            this.btnOption1_1.ButtonTextMarginLeft = 0;
            this.btnOption1_1.ColorContrastOnClick = 45;
            this.btnOption1_1.ColorContrastOnHover = 45;
            this.btnOption1_1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.btnOption1_1.CustomizableEdges = borderEdges12;
            this.btnOption1_1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnOption1_1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOption1_1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOption1_1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOption1_1.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnOption1_1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnOption1_1.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOption1_1.ForeColor = System.Drawing.Color.Gray;
            this.btnOption1_1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOption1_1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnOption1_1.IconLeftPadding = new System.Windows.Forms.Padding(23, 3, 3, 3);
            this.btnOption1_1.IconMarginLeft = 11;
            this.btnOption1_1.IconPadding = 10;
            this.btnOption1_1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOption1_1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnOption1_1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnOption1_1.IconSize = 25;
            this.btnOption1_1.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption1_1.IdleBorderRadius = 1;
            this.btnOption1_1.IdleBorderThickness = 1;
            this.btnOption1_1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption1_1.IdleIconLeftImage = null;
            this.btnOption1_1.IdleIconRightImage = null;
            this.btnOption1_1.IndicateFocus = true;
            this.btnOption1_1.Location = new System.Drawing.Point(3, 3);
            this.btnOption1_1.Name = "btnOption1_1";
            this.btnOption1_1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOption1_1.OnDisabledState.BorderRadius = 1;
            this.btnOption1_1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption1_1.OnDisabledState.BorderThickness = 1;
            this.btnOption1_1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOption1_1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOption1_1.OnDisabledState.IconLeftImage = null;
            this.btnOption1_1.OnDisabledState.IconRightImage = null;
            this.btnOption1_1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(73)))), ((int)(((byte)(79)))));
            this.btnOption1_1.onHoverState.BorderRadius = 1;
            this.btnOption1_1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption1_1.onHoverState.BorderThickness = 1;
            this.btnOption1_1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(73)))), ((int)(((byte)(79)))));
            this.btnOption1_1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnOption1_1.onHoverState.IconLeftImage = null;
            this.btnOption1_1.onHoverState.IconRightImage = null;
            this.btnOption1_1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption1_1.OnIdleState.BorderRadius = 1;
            this.btnOption1_1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption1_1.OnIdleState.BorderThickness = 1;
            this.btnOption1_1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption1_1.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btnOption1_1.OnIdleState.IconLeftImage = null;
            this.btnOption1_1.OnIdleState.IconRightImage = null;
            this.btnOption1_1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(64)))), ((int)(((byte)(69)))));
            this.btnOption1_1.OnPressedState.BorderRadius = 1;
            this.btnOption1_1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption1_1.OnPressedState.BorderThickness = 1;
            this.btnOption1_1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(64)))), ((int)(((byte)(69)))));
            this.btnOption1_1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnOption1_1.OnPressedState.IconLeftImage = null;
            this.btnOption1_1.OnPressedState.IconRightImage = null;
            this.btnOption1_1.Size = new System.Drawing.Size(220, 45);
            this.btnOption1_1.TabIndex = 0;
            this.btnOption1_1.Tag = "0";
            this.btnOption1_1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOption1_1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnOption1_1.TextMarginLeft = 0;
            this.btnOption1_1.TextPadding = new System.Windows.Forms.Padding(25, 0, 0, 0);
            this.btnOption1_1.UseDefaultRadiusAndThickness = true;
            // 
            // tabPage3
            // 
            this.tabPage3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.tabPage3.Controls.Add(this.btnOption2_2);
            this.tabPage3.Controls.Add(this.btnOption2_1);
            this.tabPage3.Location = new System.Drawing.Point(4, 22);
            this.tabPage3.Name = "tabPage3";
            this.tabPage3.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tabPage3.Size = new System.Drawing.Size(226, 682);
            this.tabPage3.TabIndex = 2;
            this.tabPage3.Text = "1";
            // 
            // btnOption2_2
            // 
            this.btnOption2_2.AllowAnimations = false;
            this.btnOption2_2.AllowMouseEffects = true;
            this.btnOption2_2.AllowToggling = true;
            this.btnOption2_2.AnimationSpeed = 200;
            this.btnOption2_2.AutoGenerateColors = false;
            this.btnOption2_2.AutoRoundBorders = false;
            this.btnOption2_2.AutoSizeLeftIcon = true;
            this.btnOption2_2.AutoSizeRightIcon = true;
            this.btnOption2_2.BackColor = System.Drawing.Color.Transparent;
            this.btnOption2_2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption2_2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnOption2_2.BackgroundImage")));
            this.btnOption2_2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption2_2.ButtonText = "Registrar Tutor";
            this.btnOption2_2.ButtonTextMarginLeft = 0;
            this.btnOption2_2.ColorContrastOnClick = 45;
            this.btnOption2_2.ColorContrastOnHover = 45;
            this.btnOption2_2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges13.BottomLeft = true;
            borderEdges13.BottomRight = true;
            borderEdges13.TopLeft = true;
            borderEdges13.TopRight = true;
            this.btnOption2_2.CustomizableEdges = borderEdges13;
            this.btnOption2_2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnOption2_2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOption2_2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOption2_2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOption2_2.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnOption2_2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnOption2_2.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOption2_2.ForeColor = System.Drawing.Color.Gray;
            this.btnOption2_2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOption2_2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnOption2_2.IconLeftPadding = new System.Windows.Forms.Padding(23, 3, 3, 3);
            this.btnOption2_2.IconMarginLeft = 11;
            this.btnOption2_2.IconPadding = 10;
            this.btnOption2_2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOption2_2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnOption2_2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnOption2_2.IconSize = 25;
            this.btnOption2_2.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption2_2.IdleBorderRadius = 1;
            this.btnOption2_2.IdleBorderThickness = 1;
            this.btnOption2_2.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption2_2.IdleIconLeftImage = null;
            this.btnOption2_2.IdleIconRightImage = null;
            this.btnOption2_2.IndicateFocus = true;
            this.btnOption2_2.Location = new System.Drawing.Point(3, 48);
            this.btnOption2_2.Name = "btnOption2_2";
            this.btnOption2_2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOption2_2.OnDisabledState.BorderRadius = 1;
            this.btnOption2_2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption2_2.OnDisabledState.BorderThickness = 1;
            this.btnOption2_2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOption2_2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOption2_2.OnDisabledState.IconLeftImage = null;
            this.btnOption2_2.OnDisabledState.IconRightImage = null;
            this.btnOption2_2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(73)))), ((int)(((byte)(79)))));
            this.btnOption2_2.onHoverState.BorderRadius = 1;
            this.btnOption2_2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption2_2.onHoverState.BorderThickness = 1;
            this.btnOption2_2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(73)))), ((int)(((byte)(79)))));
            this.btnOption2_2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnOption2_2.onHoverState.IconLeftImage = null;
            this.btnOption2_2.onHoverState.IconRightImage = null;
            this.btnOption2_2.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption2_2.OnIdleState.BorderRadius = 1;
            this.btnOption2_2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption2_2.OnIdleState.BorderThickness = 1;
            this.btnOption2_2.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption2_2.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btnOption2_2.OnIdleState.IconLeftImage = null;
            this.btnOption2_2.OnIdleState.IconRightImage = null;
            this.btnOption2_2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(64)))), ((int)(((byte)(69)))));
            this.btnOption2_2.OnPressedState.BorderRadius = 1;
            this.btnOption2_2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption2_2.OnPressedState.BorderThickness = 1;
            this.btnOption2_2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(64)))), ((int)(((byte)(69)))));
            this.btnOption2_2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnOption2_2.OnPressedState.IconLeftImage = null;
            this.btnOption2_2.OnPressedState.IconRightImage = null;
            this.btnOption2_2.Size = new System.Drawing.Size(220, 45);
            this.btnOption2_2.TabIndex = 4;
            this.btnOption2_2.Tag = "0";
            this.btnOption2_2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOption2_2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnOption2_2.TextMarginLeft = 0;
            this.btnOption2_2.TextPadding = new System.Windows.Forms.Padding(25, 0, 0, 0);
            this.btnOption2_2.UseDefaultRadiusAndThickness = true;
            this.btnOption2_2.Click += new System.EventHandler(this.btnOption2_2_Click);
            // 
            // btnOption2_1
            // 
            this.btnOption2_1.AllowAnimations = false;
            this.btnOption2_1.AllowMouseEffects = true;
            this.btnOption2_1.AllowToggling = true;
            this.btnOption2_1.AnimationSpeed = 200;
            this.btnOption2_1.AutoGenerateColors = false;
            this.btnOption2_1.AutoRoundBorders = false;
            this.btnOption2_1.AutoSizeLeftIcon = true;
            this.btnOption2_1.AutoSizeRightIcon = true;
            this.btnOption2_1.BackColor = System.Drawing.Color.Transparent;
            this.btnOption2_1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption2_1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnOption2_1.BackgroundImage")));
            this.btnOption2_1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption2_1.ButtonText = "General";
            this.btnOption2_1.ButtonTextMarginLeft = 0;
            this.btnOption2_1.ColorContrastOnClick = 45;
            this.btnOption2_1.ColorContrastOnHover = 45;
            this.btnOption2_1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges14.BottomLeft = true;
            borderEdges14.BottomRight = true;
            borderEdges14.TopLeft = true;
            borderEdges14.TopRight = true;
            this.btnOption2_1.CustomizableEdges = borderEdges14;
            this.btnOption2_1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnOption2_1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOption2_1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOption2_1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOption2_1.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnOption2_1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnOption2_1.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOption2_1.ForeColor = System.Drawing.Color.Gray;
            this.btnOption2_1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOption2_1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnOption2_1.IconLeftPadding = new System.Windows.Forms.Padding(23, 3, 3, 3);
            this.btnOption2_1.IconMarginLeft = 11;
            this.btnOption2_1.IconPadding = 10;
            this.btnOption2_1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOption2_1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnOption2_1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnOption2_1.IconSize = 25;
            this.btnOption2_1.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption2_1.IdleBorderRadius = 1;
            this.btnOption2_1.IdleBorderThickness = 1;
            this.btnOption2_1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption2_1.IdleIconLeftImage = null;
            this.btnOption2_1.IdleIconRightImage = null;
            this.btnOption2_1.IndicateFocus = true;
            this.btnOption2_1.Location = new System.Drawing.Point(3, 3);
            this.btnOption2_1.Name = "btnOption2_1";
            this.btnOption2_1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOption2_1.OnDisabledState.BorderRadius = 1;
            this.btnOption2_1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption2_1.OnDisabledState.BorderThickness = 1;
            this.btnOption2_1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOption2_1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOption2_1.OnDisabledState.IconLeftImage = null;
            this.btnOption2_1.OnDisabledState.IconRightImage = null;
            this.btnOption2_1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(73)))), ((int)(((byte)(79)))));
            this.btnOption2_1.onHoverState.BorderRadius = 1;
            this.btnOption2_1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption2_1.onHoverState.BorderThickness = 1;
            this.btnOption2_1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(73)))), ((int)(((byte)(79)))));
            this.btnOption2_1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnOption2_1.onHoverState.IconLeftImage = null;
            this.btnOption2_1.onHoverState.IconRightImage = null;
            this.btnOption2_1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption2_1.OnIdleState.BorderRadius = 1;
            this.btnOption2_1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption2_1.OnIdleState.BorderThickness = 1;
            this.btnOption2_1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption2_1.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btnOption2_1.OnIdleState.IconLeftImage = null;
            this.btnOption2_1.OnIdleState.IconRightImage = null;
            this.btnOption2_1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(64)))), ((int)(((byte)(69)))));
            this.btnOption2_1.OnPressedState.BorderRadius = 1;
            this.btnOption2_1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption2_1.OnPressedState.BorderThickness = 1;
            this.btnOption2_1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(64)))), ((int)(((byte)(69)))));
            this.btnOption2_1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnOption2_1.OnPressedState.IconLeftImage = null;
            this.btnOption2_1.OnPressedState.IconRightImage = null;
            this.btnOption2_1.Size = new System.Drawing.Size(220, 45);
            this.btnOption2_1.TabIndex = 3;
            this.btnOption2_1.Tag = "0";
            this.btnOption2_1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOption2_1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnOption2_1.TextMarginLeft = 0;
            this.btnOption2_1.TextPadding = new System.Windows.Forms.Padding(25, 0, 0, 0);
            this.btnOption2_1.UseDefaultRadiusAndThickness = true;
            this.btnOption2_1.Click += new System.EventHandler(this.btnOption2_1_Click);
            // 
            // tabPage2
            // 
            this.tabPage2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.tabPage2.Controls.Add(this.btnOption3_3);
            this.tabPage2.Controls.Add(this.btnOption3_2);
            this.tabPage2.Controls.Add(this.btnOption3_1);
            this.tabPage2.Location = new System.Drawing.Point(4, 22);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3, 3, 3, 3);
            this.tabPage2.Size = new System.Drawing.Size(226, 682);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "2";
            // 
            // btnOption3_3
            // 
            this.btnOption3_3.AllowAnimations = false;
            this.btnOption3_3.AllowMouseEffects = true;
            this.btnOption3_3.AllowToggling = true;
            this.btnOption3_3.AnimationSpeed = 200;
            this.btnOption3_3.AutoGenerateColors = false;
            this.btnOption3_3.AutoRoundBorders = false;
            this.btnOption3_3.AutoSizeLeftIcon = true;
            this.btnOption3_3.AutoSizeRightIcon = true;
            this.btnOption3_3.BackColor = System.Drawing.Color.Transparent;
            this.btnOption3_3.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption3_3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnOption3_3.BackgroundImage")));
            this.btnOption3_3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption3_3.ButtonText = "Inhabilitados";
            this.btnOption3_3.ButtonTextMarginLeft = 0;
            this.btnOption3_3.ColorContrastOnClick = 45;
            this.btnOption3_3.ColorContrastOnHover = 45;
            this.btnOption3_3.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges15.BottomLeft = true;
            borderEdges15.BottomRight = true;
            borderEdges15.TopLeft = true;
            borderEdges15.TopRight = true;
            this.btnOption3_3.CustomizableEdges = borderEdges15;
            this.btnOption3_3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnOption3_3.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOption3_3.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOption3_3.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOption3_3.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnOption3_3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnOption3_3.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOption3_3.ForeColor = System.Drawing.Color.Gray;
            this.btnOption3_3.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOption3_3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnOption3_3.IconLeftPadding = new System.Windows.Forms.Padding(23, 3, 3, 3);
            this.btnOption3_3.IconMarginLeft = 11;
            this.btnOption3_3.IconPadding = 10;
            this.btnOption3_3.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOption3_3.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnOption3_3.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnOption3_3.IconSize = 25;
            this.btnOption3_3.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption3_3.IdleBorderRadius = 1;
            this.btnOption3_3.IdleBorderThickness = 1;
            this.btnOption3_3.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption3_3.IdleIconLeftImage = null;
            this.btnOption3_3.IdleIconRightImage = null;
            this.btnOption3_3.IndicateFocus = true;
            this.btnOption3_3.Location = new System.Drawing.Point(3, 93);
            this.btnOption3_3.Name = "btnOption3_3";
            this.btnOption3_3.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOption3_3.OnDisabledState.BorderRadius = 1;
            this.btnOption3_3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption3_3.OnDisabledState.BorderThickness = 1;
            this.btnOption3_3.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOption3_3.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOption3_3.OnDisabledState.IconLeftImage = null;
            this.btnOption3_3.OnDisabledState.IconRightImage = null;
            this.btnOption3_3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(73)))), ((int)(((byte)(79)))));
            this.btnOption3_3.onHoverState.BorderRadius = 1;
            this.btnOption3_3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption3_3.onHoverState.BorderThickness = 1;
            this.btnOption3_3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(73)))), ((int)(((byte)(79)))));
            this.btnOption3_3.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnOption3_3.onHoverState.IconLeftImage = null;
            this.btnOption3_3.onHoverState.IconRightImage = null;
            this.btnOption3_3.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption3_3.OnIdleState.BorderRadius = 1;
            this.btnOption3_3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption3_3.OnIdleState.BorderThickness = 1;
            this.btnOption3_3.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption3_3.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btnOption3_3.OnIdleState.IconLeftImage = null;
            this.btnOption3_3.OnIdleState.IconRightImage = null;
            this.btnOption3_3.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(64)))), ((int)(((byte)(69)))));
            this.btnOption3_3.OnPressedState.BorderRadius = 1;
            this.btnOption3_3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption3_3.OnPressedState.BorderThickness = 1;
            this.btnOption3_3.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(64)))), ((int)(((byte)(69)))));
            this.btnOption3_3.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnOption3_3.OnPressedState.IconLeftImage = null;
            this.btnOption3_3.OnPressedState.IconRightImage = null;
            this.btnOption3_3.Size = new System.Drawing.Size(220, 45);
            this.btnOption3_3.TabIndex = 3;
            this.btnOption3_3.Tag = "0";
            this.btnOption3_3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOption3_3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnOption3_3.TextMarginLeft = 0;
            this.btnOption3_3.TextPadding = new System.Windows.Forms.Padding(25, 0, 0, 0);
            this.btnOption3_3.UseDefaultRadiusAndThickness = true;
            this.btnOption3_3.Click += new System.EventHandler(this.btnOption3_3_Click);
            // 
            // btnOption3_2
            // 
            this.btnOption3_2.AllowAnimations = false;
            this.btnOption3_2.AllowMouseEffects = true;
            this.btnOption3_2.AllowToggling = true;
            this.btnOption3_2.AnimationSpeed = 200;
            this.btnOption3_2.AutoGenerateColors = false;
            this.btnOption3_2.AutoRoundBorders = false;
            this.btnOption3_2.AutoSizeLeftIcon = true;
            this.btnOption3_2.AutoSizeRightIcon = true;
            this.btnOption3_2.BackColor = System.Drawing.Color.Transparent;
            this.btnOption3_2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption3_2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnOption3_2.BackgroundImage")));
            this.btnOption3_2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption3_2.ButtonText = "Detalles Estudiante";
            this.btnOption3_2.ButtonTextMarginLeft = 0;
            this.btnOption3_2.ColorContrastOnClick = 45;
            this.btnOption3_2.ColorContrastOnHover = 45;
            this.btnOption3_2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges16.BottomLeft = true;
            borderEdges16.BottomRight = true;
            borderEdges16.TopLeft = true;
            borderEdges16.TopRight = true;
            this.btnOption3_2.CustomizableEdges = borderEdges16;
            this.btnOption3_2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnOption3_2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOption3_2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOption3_2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOption3_2.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnOption3_2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnOption3_2.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOption3_2.ForeColor = System.Drawing.Color.Gray;
            this.btnOption3_2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOption3_2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnOption3_2.IconLeftPadding = new System.Windows.Forms.Padding(23, 3, 3, 3);
            this.btnOption3_2.IconMarginLeft = 11;
            this.btnOption3_2.IconPadding = 10;
            this.btnOption3_2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOption3_2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnOption3_2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnOption3_2.IconSize = 25;
            this.btnOption3_2.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption3_2.IdleBorderRadius = 1;
            this.btnOption3_2.IdleBorderThickness = 1;
            this.btnOption3_2.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption3_2.IdleIconLeftImage = null;
            this.btnOption3_2.IdleIconRightImage = null;
            this.btnOption3_2.IndicateFocus = true;
            this.btnOption3_2.Location = new System.Drawing.Point(3, 48);
            this.btnOption3_2.Name = "btnOption3_2";
            this.btnOption3_2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOption3_2.OnDisabledState.BorderRadius = 1;
            this.btnOption3_2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption3_2.OnDisabledState.BorderThickness = 1;
            this.btnOption3_2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOption3_2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOption3_2.OnDisabledState.IconLeftImage = null;
            this.btnOption3_2.OnDisabledState.IconRightImage = null;
            this.btnOption3_2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(73)))), ((int)(((byte)(79)))));
            this.btnOption3_2.onHoverState.BorderRadius = 1;
            this.btnOption3_2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption3_2.onHoverState.BorderThickness = 1;
            this.btnOption3_2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(73)))), ((int)(((byte)(79)))));
            this.btnOption3_2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnOption3_2.onHoverState.IconLeftImage = null;
            this.btnOption3_2.onHoverState.IconRightImage = null;
            this.btnOption3_2.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption3_2.OnIdleState.BorderRadius = 1;
            this.btnOption3_2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption3_2.OnIdleState.BorderThickness = 1;
            this.btnOption3_2.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption3_2.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btnOption3_2.OnIdleState.IconLeftImage = null;
            this.btnOption3_2.OnIdleState.IconRightImage = null;
            this.btnOption3_2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(64)))), ((int)(((byte)(69)))));
            this.btnOption3_2.OnPressedState.BorderRadius = 1;
            this.btnOption3_2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption3_2.OnPressedState.BorderThickness = 1;
            this.btnOption3_2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(64)))), ((int)(((byte)(69)))));
            this.btnOption3_2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnOption3_2.OnPressedState.IconLeftImage = null;
            this.btnOption3_2.OnPressedState.IconRightImage = null;
            this.btnOption3_2.Size = new System.Drawing.Size(220, 45);
            this.btnOption3_2.TabIndex = 2;
            this.btnOption3_2.Tag = "0";
            this.btnOption3_2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOption3_2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnOption3_2.TextMarginLeft = 0;
            this.btnOption3_2.TextPadding = new System.Windows.Forms.Padding(25, 0, 0, 0);
            this.btnOption3_2.UseDefaultRadiusAndThickness = true;
            this.btnOption3_2.Click += new System.EventHandler(this.btnOption3_2_Click);
            // 
            // btnOption3_1
            // 
            this.btnOption3_1.AllowAnimations = false;
            this.btnOption3_1.AllowMouseEffects = true;
            this.btnOption3_1.AllowToggling = true;
            this.btnOption3_1.AnimationSpeed = 200;
            this.btnOption3_1.AutoGenerateColors = false;
            this.btnOption3_1.AutoRoundBorders = false;
            this.btnOption3_1.AutoSizeLeftIcon = true;
            this.btnOption3_1.AutoSizeRightIcon = true;
            this.btnOption3_1.BackColor = System.Drawing.Color.Transparent;
            this.btnOption3_1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption3_1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnOption3_1.BackgroundImage")));
            this.btnOption3_1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption3_1.ButtonText = "General";
            this.btnOption3_1.ButtonTextMarginLeft = 0;
            this.btnOption3_1.ColorContrastOnClick = 45;
            this.btnOption3_1.ColorContrastOnHover = 45;
            this.btnOption3_1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges17.BottomLeft = true;
            borderEdges17.BottomRight = true;
            borderEdges17.TopLeft = true;
            borderEdges17.TopRight = true;
            this.btnOption3_1.CustomizableEdges = borderEdges17;
            this.btnOption3_1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnOption3_1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOption3_1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOption3_1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOption3_1.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnOption3_1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnOption3_1.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOption3_1.ForeColor = System.Drawing.Color.Gray;
            this.btnOption3_1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOption3_1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnOption3_1.IconLeftPadding = new System.Windows.Forms.Padding(23, 3, 3, 3);
            this.btnOption3_1.IconMarginLeft = 11;
            this.btnOption3_1.IconPadding = 10;
            this.btnOption3_1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOption3_1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnOption3_1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnOption3_1.IconSize = 25;
            this.btnOption3_1.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption3_1.IdleBorderRadius = 1;
            this.btnOption3_1.IdleBorderThickness = 1;
            this.btnOption3_1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption3_1.IdleIconLeftImage = null;
            this.btnOption3_1.IdleIconRightImage = null;
            this.btnOption3_1.IndicateFocus = true;
            this.btnOption3_1.Location = new System.Drawing.Point(3, 3);
            this.btnOption3_1.Name = "btnOption3_1";
            this.btnOption3_1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOption3_1.OnDisabledState.BorderRadius = 1;
            this.btnOption3_1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption3_1.OnDisabledState.BorderThickness = 1;
            this.btnOption3_1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOption3_1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOption3_1.OnDisabledState.IconLeftImage = null;
            this.btnOption3_1.OnDisabledState.IconRightImage = null;
            this.btnOption3_1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(73)))), ((int)(((byte)(79)))));
            this.btnOption3_1.onHoverState.BorderRadius = 1;
            this.btnOption3_1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption3_1.onHoverState.BorderThickness = 1;
            this.btnOption3_1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(73)))), ((int)(((byte)(79)))));
            this.btnOption3_1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnOption3_1.onHoverState.IconLeftImage = null;
            this.btnOption3_1.onHoverState.IconRightImage = null;
            this.btnOption3_1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption3_1.OnIdleState.BorderRadius = 1;
            this.btnOption3_1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption3_1.OnIdleState.BorderThickness = 1;
            this.btnOption3_1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption3_1.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btnOption3_1.OnIdleState.IconLeftImage = null;
            this.btnOption3_1.OnIdleState.IconRightImage = null;
            this.btnOption3_1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(64)))), ((int)(((byte)(69)))));
            this.btnOption3_1.OnPressedState.BorderRadius = 1;
            this.btnOption3_1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption3_1.OnPressedState.BorderThickness = 1;
            this.btnOption3_1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(64)))), ((int)(((byte)(69)))));
            this.btnOption3_1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnOption3_1.OnPressedState.IconLeftImage = null;
            this.btnOption3_1.OnPressedState.IconRightImage = null;
            this.btnOption3_1.Size = new System.Drawing.Size(220, 45);
            this.btnOption3_1.TabIndex = 1;
            this.btnOption3_1.Tag = "0";
            this.btnOption3_1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOption3_1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnOption3_1.TextMarginLeft = 0;
            this.btnOption3_1.TextPadding = new System.Windows.Forms.Padding(25, 0, 0, 0);
            this.btnOption3_1.UseDefaultRadiusAndThickness = true;
            this.btnOption3_1.Click += new System.EventHandler(this.BtnOption3_1_Click);
            // 
            // tabPage4
            // 
            this.tabPage4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.tabPage4.Controls.Add(this.btnOpcion4_2);
            this.tabPage4.Controls.Add(this.btnOpcion4_1);
            this.tabPage4.Location = new System.Drawing.Point(4, 22);
            this.tabPage4.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.tabPage4.Name = "tabPage4";
            this.tabPage4.Padding = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.tabPage4.Size = new System.Drawing.Size(226, 682);
            this.tabPage4.TabIndex = 3;
            this.tabPage4.Text = "3";
            // 
            // btnOpcion4_2
            // 
            this.btnOpcion4_2.AllowAnimations = false;
            this.btnOpcion4_2.AllowMouseEffects = true;
            this.btnOpcion4_2.AllowToggling = true;
            this.btnOpcion4_2.AnimationSpeed = 200;
            this.btnOpcion4_2.AutoGenerateColors = false;
            this.btnOpcion4_2.AutoRoundBorders = false;
            this.btnOpcion4_2.AutoSizeLeftIcon = true;
            this.btnOpcion4_2.AutoSizeRightIcon = true;
            this.btnOpcion4_2.BackColor = System.Drawing.Color.Transparent;
            this.btnOpcion4_2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOpcion4_2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnOpcion4_2.BackgroundImage")));
            this.btnOpcion4_2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOpcion4_2.ButtonText = "Registrar Docente";
            this.btnOpcion4_2.ButtonTextMarginLeft = 0;
            this.btnOpcion4_2.ColorContrastOnClick = 45;
            this.btnOpcion4_2.ColorContrastOnHover = 45;
            this.btnOpcion4_2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges18.BottomLeft = true;
            borderEdges18.BottomRight = true;
            borderEdges18.TopLeft = true;
            borderEdges18.TopRight = true;
            this.btnOpcion4_2.CustomizableEdges = borderEdges18;
            this.btnOpcion4_2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnOpcion4_2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOpcion4_2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOpcion4_2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOpcion4_2.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnOpcion4_2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnOpcion4_2.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOpcion4_2.ForeColor = System.Drawing.Color.Gray;
            this.btnOpcion4_2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOpcion4_2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnOpcion4_2.IconLeftPadding = new System.Windows.Forms.Padding(23, 3, 3, 3);
            this.btnOpcion4_2.IconMarginLeft = 11;
            this.btnOpcion4_2.IconPadding = 10;
            this.btnOpcion4_2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOpcion4_2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnOpcion4_2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnOpcion4_2.IconSize = 25;
            this.btnOpcion4_2.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOpcion4_2.IdleBorderRadius = 1;
            this.btnOpcion4_2.IdleBorderThickness = 1;
            this.btnOpcion4_2.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOpcion4_2.IdleIconLeftImage = null;
            this.btnOpcion4_2.IdleIconRightImage = null;
            this.btnOpcion4_2.IndicateFocus = true;
            this.btnOpcion4_2.Location = new System.Drawing.Point(2, 47);
            this.btnOpcion4_2.Name = "btnOpcion4_2";
            this.btnOpcion4_2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOpcion4_2.OnDisabledState.BorderRadius = 1;
            this.btnOpcion4_2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOpcion4_2.OnDisabledState.BorderThickness = 1;
            this.btnOpcion4_2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOpcion4_2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOpcion4_2.OnDisabledState.IconLeftImage = null;
            this.btnOpcion4_2.OnDisabledState.IconRightImage = null;
            this.btnOpcion4_2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(73)))), ((int)(((byte)(79)))));
            this.btnOpcion4_2.onHoverState.BorderRadius = 1;
            this.btnOpcion4_2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOpcion4_2.onHoverState.BorderThickness = 1;
            this.btnOpcion4_2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(73)))), ((int)(((byte)(79)))));
            this.btnOpcion4_2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnOpcion4_2.onHoverState.IconLeftImage = null;
            this.btnOpcion4_2.onHoverState.IconRightImage = null;
            this.btnOpcion4_2.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOpcion4_2.OnIdleState.BorderRadius = 1;
            this.btnOpcion4_2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOpcion4_2.OnIdleState.BorderThickness = 1;
            this.btnOpcion4_2.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOpcion4_2.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btnOpcion4_2.OnIdleState.IconLeftImage = null;
            this.btnOpcion4_2.OnIdleState.IconRightImage = null;
            this.btnOpcion4_2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(64)))), ((int)(((byte)(69)))));
            this.btnOpcion4_2.OnPressedState.BorderRadius = 1;
            this.btnOpcion4_2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOpcion4_2.OnPressedState.BorderThickness = 1;
            this.btnOpcion4_2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(64)))), ((int)(((byte)(69)))));
            this.btnOpcion4_2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnOpcion4_2.OnPressedState.IconLeftImage = null;
            this.btnOpcion4_2.OnPressedState.IconRightImage = null;
            this.btnOpcion4_2.Size = new System.Drawing.Size(222, 45);
            this.btnOpcion4_2.TabIndex = 3;
            this.btnOpcion4_2.Tag = "0";
            this.btnOpcion4_2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOpcion4_2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnOpcion4_2.TextMarginLeft = 0;
            this.btnOpcion4_2.TextPadding = new System.Windows.Forms.Padding(25, 0, 0, 0);
            this.btnOpcion4_2.UseDefaultRadiusAndThickness = true;
            this.btnOpcion4_2.Click += new System.EventHandler(this.btnOpcion4_2_Click);
            // 
            // btnOpcion4_1
            // 
            this.btnOpcion4_1.AllowAnimations = false;
            this.btnOpcion4_1.AllowMouseEffects = true;
            this.btnOpcion4_1.AllowToggling = true;
            this.btnOpcion4_1.AnimationSpeed = 200;
            this.btnOpcion4_1.AutoGenerateColors = false;
            this.btnOpcion4_1.AutoRoundBorders = false;
            this.btnOpcion4_1.AutoSizeLeftIcon = true;
            this.btnOpcion4_1.AutoSizeRightIcon = true;
            this.btnOpcion4_1.BackColor = System.Drawing.Color.Transparent;
            this.btnOpcion4_1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOpcion4_1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnOpcion4_1.BackgroundImage")));
            this.btnOpcion4_1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOpcion4_1.ButtonText = "General";
            this.btnOpcion4_1.ButtonTextMarginLeft = 0;
            this.btnOpcion4_1.ColorContrastOnClick = 45;
            this.btnOpcion4_1.ColorContrastOnHover = 45;
            this.btnOpcion4_1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges19.BottomLeft = true;
            borderEdges19.BottomRight = true;
            borderEdges19.TopLeft = true;
            borderEdges19.TopRight = true;
            this.btnOpcion4_1.CustomizableEdges = borderEdges19;
            this.btnOpcion4_1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnOpcion4_1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOpcion4_1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOpcion4_1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOpcion4_1.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnOpcion4_1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnOpcion4_1.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOpcion4_1.ForeColor = System.Drawing.Color.Gray;
            this.btnOpcion4_1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOpcion4_1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnOpcion4_1.IconLeftPadding = new System.Windows.Forms.Padding(23, 3, 3, 3);
            this.btnOpcion4_1.IconMarginLeft = 11;
            this.btnOpcion4_1.IconPadding = 10;
            this.btnOpcion4_1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOpcion4_1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnOpcion4_1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnOpcion4_1.IconSize = 25;
            this.btnOpcion4_1.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOpcion4_1.IdleBorderRadius = 1;
            this.btnOpcion4_1.IdleBorderThickness = 1;
            this.btnOpcion4_1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOpcion4_1.IdleIconLeftImage = null;
            this.btnOpcion4_1.IdleIconRightImage = null;
            this.btnOpcion4_1.IndicateFocus = true;
            this.btnOpcion4_1.Location = new System.Drawing.Point(2, 2);
            this.btnOpcion4_1.Name = "btnOpcion4_1";
            this.btnOpcion4_1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOpcion4_1.OnDisabledState.BorderRadius = 1;
            this.btnOpcion4_1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOpcion4_1.OnDisabledState.BorderThickness = 1;
            this.btnOpcion4_1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOpcion4_1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOpcion4_1.OnDisabledState.IconLeftImage = null;
            this.btnOpcion4_1.OnDisabledState.IconRightImage = null;
            this.btnOpcion4_1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(73)))), ((int)(((byte)(79)))));
            this.btnOpcion4_1.onHoverState.BorderRadius = 1;
            this.btnOpcion4_1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOpcion4_1.onHoverState.BorderThickness = 1;
            this.btnOpcion4_1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(73)))), ((int)(((byte)(79)))));
            this.btnOpcion4_1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnOpcion4_1.onHoverState.IconLeftImage = null;
            this.btnOpcion4_1.onHoverState.IconRightImage = null;
            this.btnOpcion4_1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOpcion4_1.OnIdleState.BorderRadius = 1;
            this.btnOpcion4_1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOpcion4_1.OnIdleState.BorderThickness = 1;
            this.btnOpcion4_1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOpcion4_1.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btnOpcion4_1.OnIdleState.IconLeftImage = null;
            this.btnOpcion4_1.OnIdleState.IconRightImage = null;
            this.btnOpcion4_1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(64)))), ((int)(((byte)(69)))));
            this.btnOpcion4_1.OnPressedState.BorderRadius = 1;
            this.btnOpcion4_1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOpcion4_1.OnPressedState.BorderThickness = 1;
            this.btnOpcion4_1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(64)))), ((int)(((byte)(69)))));
            this.btnOpcion4_1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnOpcion4_1.OnPressedState.IconLeftImage = null;
            this.btnOpcion4_1.OnPressedState.IconRightImage = null;
            this.btnOpcion4_1.Size = new System.Drawing.Size(222, 45);
            this.btnOpcion4_1.TabIndex = 2;
            this.btnOpcion4_1.Tag = "0";
            this.btnOpcion4_1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOpcion4_1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnOpcion4_1.TextMarginLeft = 0;
            this.btnOpcion4_1.TextPadding = new System.Windows.Forms.Padding(25, 0, 0, 0);
            this.btnOpcion4_1.UseDefaultRadiusAndThickness = true;
            this.btnOpcion4_1.Click += new System.EventHandler(this.btnOpcion4_1_Click);
            // 
            // hider
            // 
            this.hider.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.hider.Dock = System.Windows.Forms.DockStyle.Top;
            this.hider.Location = new System.Drawing.Point(0, 0);
            this.hider.Name = "hider";
            this.hider.Size = new System.Drawing.Size(220, 0);
            this.hider.TabIndex = 2;
            // 
            // tabPage5
            // 
            this.tabPage5.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.tabPage5.Controls.Add(this.btnOption5_1);
            this.tabPage5.Location = new System.Drawing.Point(4, 22);
            this.tabPage5.Name = "tabPage5";
            this.tabPage5.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage5.Size = new System.Drawing.Size(226, 682);
            this.tabPage5.TabIndex = 4;
            this.tabPage5.Text = "4";
            // 
            // btnOption5_1
            // 
            this.btnOption5_1.AllowAnimations = false;
            this.btnOption5_1.AllowMouseEffects = true;
            this.btnOption5_1.AllowToggling = true;
            this.btnOption5_1.AnimationSpeed = 200;
            this.btnOption5_1.AutoGenerateColors = false;
            this.btnOption5_1.AutoRoundBorders = false;
            this.btnOption5_1.AutoSizeLeftIcon = true;
            this.btnOption5_1.AutoSizeRightIcon = true;
            this.btnOption5_1.BackColor = System.Drawing.Color.Transparent;
            this.btnOption5_1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption5_1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnOption5_1.BackgroundImage")));
            this.btnOption5_1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption5_1.ButtonText = "General";
            this.btnOption5_1.ButtonTextMarginLeft = 0;
            this.btnOption5_1.ColorContrastOnClick = 45;
            this.btnOption5_1.ColorContrastOnHover = 45;
            this.btnOption5_1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges20.BottomLeft = true;
            borderEdges20.BottomRight = true;
            borderEdges20.TopLeft = true;
            borderEdges20.TopRight = true;
            this.btnOption5_1.CustomizableEdges = borderEdges20;
            this.btnOption5_1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnOption5_1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOption5_1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOption5_1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOption5_1.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnOption5_1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnOption5_1.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOption5_1.ForeColor = System.Drawing.Color.Gray;
            this.btnOption5_1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOption5_1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnOption5_1.IconLeftPadding = new System.Windows.Forms.Padding(23, 3, 3, 3);
            this.btnOption5_1.IconMarginLeft = 11;
            this.btnOption5_1.IconPadding = 10;
            this.btnOption5_1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOption5_1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnOption5_1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnOption5_1.IconSize = 25;
            this.btnOption5_1.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption5_1.IdleBorderRadius = 1;
            this.btnOption5_1.IdleBorderThickness = 1;
            this.btnOption5_1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption5_1.IdleIconLeftImage = null;
            this.btnOption5_1.IdleIconRightImage = null;
            this.btnOption5_1.IndicateFocus = true;
            this.btnOption5_1.Location = new System.Drawing.Point(3, 3);
            this.btnOption5_1.Name = "btnOption5_1";
            this.btnOption5_1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnOption5_1.OnDisabledState.BorderRadius = 1;
            this.btnOption5_1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption5_1.OnDisabledState.BorderThickness = 1;
            this.btnOption5_1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnOption5_1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnOption5_1.OnDisabledState.IconLeftImage = null;
            this.btnOption5_1.OnDisabledState.IconRightImage = null;
            this.btnOption5_1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(73)))), ((int)(((byte)(79)))));
            this.btnOption5_1.onHoverState.BorderRadius = 1;
            this.btnOption5_1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption5_1.onHoverState.BorderThickness = 1;
            this.btnOption5_1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(68)))), ((int)(((byte)(73)))), ((int)(((byte)(79)))));
            this.btnOption5_1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnOption5_1.onHoverState.IconLeftImage = null;
            this.btnOption5_1.onHoverState.IconRightImage = null;
            this.btnOption5_1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption5_1.OnIdleState.BorderRadius = 1;
            this.btnOption5_1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption5_1.OnIdleState.BorderThickness = 1;
            this.btnOption5_1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(36)))), ((int)(((byte)(42)))), ((int)(((byte)(49)))));
            this.btnOption5_1.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btnOption5_1.OnIdleState.IconLeftImage = null;
            this.btnOption5_1.OnIdleState.IconRightImage = null;
            this.btnOption5_1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(64)))), ((int)(((byte)(69)))));
            this.btnOption5_1.OnPressedState.BorderRadius = 1;
            this.btnOption5_1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOption5_1.OnPressedState.BorderThickness = 1;
            this.btnOption5_1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(61)))), ((int)(((byte)(64)))), ((int)(((byte)(69)))));
            this.btnOption5_1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnOption5_1.OnPressedState.IconLeftImage = null;
            this.btnOption5_1.OnPressedState.IconRightImage = null;
            this.btnOption5_1.Size = new System.Drawing.Size(220, 45);
            this.btnOption5_1.TabIndex = 3;
            this.btnOption5_1.Tag = "0";
            this.btnOption5_1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOption5_1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnOption5_1.TextMarginLeft = 0;
            this.btnOption5_1.TextPadding = new System.Windows.Forms.Padding(25, 0, 0, 0);
            this.btnOption5_1.UseDefaultRadiusAndThickness = true;
            this.btnOption5_1.Click += new System.EventHandler(this.btnOption5_1_Click);
            // 
            // frmSubMenu
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.hider);
            this.Controls.Add(this.tabControl1);
            this.Name = "frmSubMenu";
            this.Size = new System.Drawing.Size(220, 698);
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage3.ResumeLayout(false);
            this.tabPage2.ResumeLayout(false);
            this.tabPage4.ResumeLayout(false);
            this.tabPage5.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.TabPage tabPage2;
        private System.Windows.Forms.TabPage tabPage3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnOption1_1;
        private System.Windows.Forms.Panel hider;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnOption3_1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnOption3_3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnOption3_2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnOption1_2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnOption2_2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnOption2_1;
        private System.Windows.Forms.TabPage tabPage4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnOpcion4_2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnOpcion4_1;
        private System.Windows.Forms.TabPage tabPage5;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnOption5_1;
    }
}
