
namespace CapaPresentacion.Detalles
{
    partial class DocenteDetalle
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(DocenteDetalle));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.imgDocPerfil = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.label27 = new System.Windows.Forms.Label();
            this.txtDocTelefono = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtDocNombre = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblParEstNombre = new System.Windows.Forms.Label();
            this.txtDocDni = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label25 = new System.Windows.Forms.Label();
            this.lblParamEstDni = new System.Windows.Forms.Label();
            this.txtDocApMaterno = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtDocApPaterno = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblParEstApellido = new System.Windows.Forms.Label();
            this.label26 = new System.Windows.Forms.Label();
            this.btnConfirmarDoc = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnImageDoc = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnEditarDoc = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtDocEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.gbDoc = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.rdbDocMasculino = new Bunifu.UI.WinForms.BunifuRadioButton();
            this.lblMasculino = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblFemenino = new Bunifu.UI.WinForms.BunifuLabel();
            this.rdbDocFemenino = new Bunifu.UI.WinForms.BunifuRadioButton();
            this.lblParEstDireccion = new System.Windows.Forms.Label();
            this.dpkDocFecNacimiento = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.txtDocDireccion = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblParEstFechaNac = new System.Windows.Forms.Label();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.label1 = new System.Windows.Forms.Label();
            this.txtDocEsp = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            ((System.ComponentModel.ISupportInitialize)(this.imgDocPerfil)).BeginInit();
            this.gbDoc.SuspendLayout();
            this.SuspendLayout();
            // 
            // imgDocPerfil
            // 
            this.imgDocPerfil.AllowFocused = false;
            this.imgDocPerfil.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.imgDocPerfil.AutoSizeHeight = true;
            this.imgDocPerfil.BorderRadius = 102;
            this.imgDocPerfil.Image = ((System.Drawing.Image)(resources.GetObject("imgDocPerfil.Image")));
            this.imgDocPerfil.IsCircle = true;
            this.imgDocPerfil.Location = new System.Drawing.Point(290, -1);
            this.imgDocPerfil.Name = "imgDocPerfil";
            this.imgDocPerfil.Size = new System.Drawing.Size(204, 204);
            this.imgDocPerfil.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.imgDocPerfil.TabIndex = 65;
            this.imgDocPerfil.TabStop = false;
            this.imgDocPerfil.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // label27
            // 
            this.label27.AutoSize = true;
            this.label27.BackColor = System.Drawing.Color.Transparent;
            this.label27.Enabled = false;
            this.label27.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label27.ForeColor = System.Drawing.Color.DimGray;
            this.label27.Location = new System.Drawing.Point(412, 432);
            this.label27.Name = "label27";
            this.label27.Size = new System.Drawing.Size(67, 20);
            this.label27.TabIndex = 64;
            this.label27.Text = "Telefono";
            // 
            // txtDocTelefono
            // 
            this.txtDocTelefono.AcceptsReturn = false;
            this.txtDocTelefono.AcceptsTab = false;
            this.txtDocTelefono.AnimationSpeed = 200;
            this.txtDocTelefono.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDocTelefono.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDocTelefono.BackColor = System.Drawing.Color.White;
            this.txtDocTelefono.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDocTelefono.BackgroundImage")));
            this.txtDocTelefono.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDocTelefono.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDocTelefono.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDocTelefono.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDocTelefono.BorderRadius = 10;
            this.txtDocTelefono.BorderThickness = 1;
            this.txtDocTelefono.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDocTelefono.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocTelefono.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDocTelefono.DefaultText = "";
            this.txtDocTelefono.FillColor = System.Drawing.Color.White;
            this.txtDocTelefono.HideSelection = true;
            this.txtDocTelefono.IconLeft = null;
            this.txtDocTelefono.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocTelefono.IconPadding = 10;
            this.txtDocTelefono.IconRight = null;
            this.txtDocTelefono.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocTelefono.Lines = new string[0];
            this.txtDocTelefono.Location = new System.Drawing.Point(413, 455);
            this.txtDocTelefono.MaxLength = 9;
            this.txtDocTelefono.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDocTelefono.Modified = false;
            this.txtDocTelefono.Multiline = false;
            this.txtDocTelefono.Name = "txtDocTelefono";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocTelefono.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDocTelefono.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocTelefono.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocTelefono.OnIdleState = stateProperties4;
            this.txtDocTelefono.Padding = new System.Windows.Forms.Padding(3);
            this.txtDocTelefono.PasswordChar = '\0';
            this.txtDocTelefono.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDocTelefono.PlaceholderText = "Telefono";
            this.txtDocTelefono.ReadOnly = true;
            this.txtDocTelefono.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDocTelefono.SelectedText = "";
            this.txtDocTelefono.SelectionLength = 0;
            this.txtDocTelefono.SelectionStart = 0;
            this.txtDocTelefono.ShortcutsEnabled = true;
            this.txtDocTelefono.Size = new System.Drawing.Size(281, 37);
            this.txtDocTelefono.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtDocTelefono.TabIndex = 5;
            this.txtDocTelefono.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDocTelefono.TextMarginBottom = 0;
            this.txtDocTelefono.TextMarginLeft = 3;
            this.txtDocTelefono.TextMarginTop = 0;
            this.txtDocTelefono.TextPlaceholder = "Telefono";
            this.txtDocTelefono.UseSystemPasswordChar = false;
            this.txtDocTelefono.WordWrap = true;
            // 
            // txtDocNombre
            // 
            this.txtDocNombre.AcceptsReturn = false;
            this.txtDocNombre.AcceptsTab = false;
            this.txtDocNombre.AnimationSpeed = 200;
            this.txtDocNombre.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDocNombre.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDocNombre.BackColor = System.Drawing.Color.White;
            this.txtDocNombre.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDocNombre.BackgroundImage")));
            this.txtDocNombre.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDocNombre.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDocNombre.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDocNombre.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDocNombre.BorderRadius = 10;
            this.txtDocNombre.BorderThickness = 1;
            this.txtDocNombre.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDocNombre.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocNombre.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDocNombre.DefaultText = "";
            this.txtDocNombre.FillColor = System.Drawing.Color.White;
            this.txtDocNombre.HideSelection = true;
            this.txtDocNombre.IconLeft = null;
            this.txtDocNombre.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocNombre.IconPadding = 10;
            this.txtDocNombre.IconRight = null;
            this.txtDocNombre.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocNombre.Lines = new string[0];
            this.txtDocNombre.Location = new System.Drawing.Point(104, 237);
            this.txtDocNombre.MaxLength = 32767;
            this.txtDocNombre.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDocNombre.Modified = false;
            this.txtDocNombre.Multiline = false;
            this.txtDocNombre.Name = "txtDocNombre";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocNombre.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDocNombre.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocNombre.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocNombre.OnIdleState = stateProperties8;
            this.txtDocNombre.Padding = new System.Windows.Forms.Padding(3);
            this.txtDocNombre.PasswordChar = '\0';
            this.txtDocNombre.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDocNombre.PlaceholderText = "Nombres";
            this.txtDocNombre.ReadOnly = true;
            this.txtDocNombre.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDocNombre.SelectedText = "";
            this.txtDocNombre.SelectionLength = 0;
            this.txtDocNombre.SelectionStart = 0;
            this.txtDocNombre.ShortcutsEnabled = true;
            this.txtDocNombre.Size = new System.Drawing.Size(590, 37);
            this.txtDocNombre.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtDocNombre.TabIndex = 1;
            this.txtDocNombre.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDocNombre.TextMarginBottom = 0;
            this.txtDocNombre.TextMarginLeft = 3;
            this.txtDocNombre.TextMarginTop = 0;
            this.txtDocNombre.TextPlaceholder = "Nombres";
            this.txtDocNombre.UseSystemPasswordChar = false;
            this.txtDocNombre.WordWrap = true;
            // 
            // lblParEstNombre
            // 
            this.lblParEstNombre.AutoSize = true;
            this.lblParEstNombre.BackColor = System.Drawing.Color.Transparent;
            this.lblParEstNombre.Enabled = false;
            this.lblParEstNombre.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblParEstNombre.ForeColor = System.Drawing.Color.DimGray;
            this.lblParEstNombre.Location = new System.Drawing.Point(103, 214);
            this.lblParEstNombre.Name = "lblParEstNombre";
            this.lblParEstNombre.Size = new System.Drawing.Size(70, 20);
            this.lblParEstNombre.TabIndex = 60;
            this.lblParEstNombre.Text = "Nombres";
            // 
            // txtDocDni
            // 
            this.txtDocDni.AcceptsReturn = false;
            this.txtDocDni.AcceptsTab = false;
            this.txtDocDni.AnimationSpeed = 200;
            this.txtDocDni.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDocDni.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDocDni.BackColor = System.Drawing.Color.White;
            this.txtDocDni.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDocDni.BackgroundImage")));
            this.txtDocDni.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDocDni.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDocDni.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDocDni.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDocDni.BorderRadius = 10;
            this.txtDocDni.BorderThickness = 1;
            this.txtDocDni.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDocDni.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocDni.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDocDni.DefaultText = "";
            this.txtDocDni.FillColor = System.Drawing.Color.White;
            this.txtDocDni.HideSelection = true;
            this.txtDocDni.IconLeft = null;
            this.txtDocDni.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocDni.IconPadding = 10;
            this.txtDocDni.IconRight = null;
            this.txtDocDni.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocDni.Lines = new string[0];
            this.txtDocDni.Location = new System.Drawing.Point(104, 455);
            this.txtDocDni.MaxLength = 8;
            this.txtDocDni.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDocDni.Modified = false;
            this.txtDocDni.Multiline = false;
            this.txtDocDni.Name = "txtDocDni";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocDni.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDocDni.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocDni.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocDni.OnIdleState = stateProperties12;
            this.txtDocDni.Padding = new System.Windows.Forms.Padding(3);
            this.txtDocDni.PasswordChar = '\0';
            this.txtDocDni.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDocDni.PlaceholderText = "Dni";
            this.txtDocDni.ReadOnly = true;
            this.txtDocDni.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDocDni.SelectedText = "";
            this.txtDocDni.SelectionLength = 0;
            this.txtDocDni.SelectionStart = 0;
            this.txtDocDni.ShortcutsEnabled = true;
            this.txtDocDni.Size = new System.Drawing.Size(252, 37);
            this.txtDocDni.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtDocDni.TabIndex = 4;
            this.txtDocDni.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDocDni.TextMarginBottom = 0;
            this.txtDocDni.TextMarginLeft = 3;
            this.txtDocDni.TextMarginTop = 0;
            this.txtDocDni.TextPlaceholder = "Dni";
            this.txtDocDni.UseSystemPasswordChar = false;
            this.txtDocDni.WordWrap = true;
            // 
            // label25
            // 
            this.label25.AutoSize = true;
            this.label25.BackColor = System.Drawing.Color.Transparent;
            this.label25.Enabled = false;
            this.label25.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label25.ForeColor = System.Drawing.Color.DimGray;
            this.label25.Location = new System.Drawing.Point(103, 359);
            this.label25.Name = "label25";
            this.label25.Size = new System.Drawing.Size(126, 20);
            this.label25.TabIndex = 63;
            this.label25.Text = "Apellido Materno";
            // 
            // lblParamEstDni
            // 
            this.lblParamEstDni.AutoSize = true;
            this.lblParamEstDni.BackColor = System.Drawing.Color.Transparent;
            this.lblParamEstDni.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblParamEstDni.Enabled = false;
            this.lblParamEstDni.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblParamEstDni.ForeColor = System.Drawing.Color.DimGray;
            this.lblParamEstDni.Location = new System.Drawing.Point(41, 362);
            this.lblParamEstDni.Name = "lblParamEstDni";
            this.lblParamEstDni.Size = new System.Drawing.Size(32, 20);
            this.lblParamEstDni.TabIndex = 61;
            this.lblParamEstDni.Text = "Dni";
            // 
            // txtDocApMaterno
            // 
            this.txtDocApMaterno.AcceptsReturn = false;
            this.txtDocApMaterno.AcceptsTab = false;
            this.txtDocApMaterno.AnimationSpeed = 200;
            this.txtDocApMaterno.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDocApMaterno.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDocApMaterno.BackColor = System.Drawing.Color.White;
            this.txtDocApMaterno.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDocApMaterno.BackgroundImage")));
            this.txtDocApMaterno.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDocApMaterno.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDocApMaterno.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDocApMaterno.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDocApMaterno.BorderRadius = 10;
            this.txtDocApMaterno.BorderThickness = 1;
            this.txtDocApMaterno.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDocApMaterno.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocApMaterno.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDocApMaterno.DefaultText = "";
            this.txtDocApMaterno.Enabled = false;
            this.txtDocApMaterno.FillColor = System.Drawing.Color.White;
            this.txtDocApMaterno.HideSelection = true;
            this.txtDocApMaterno.IconLeft = null;
            this.txtDocApMaterno.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocApMaterno.IconPadding = 10;
            this.txtDocApMaterno.IconRight = null;
            this.txtDocApMaterno.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocApMaterno.Lines = new string[0];
            this.txtDocApMaterno.Location = new System.Drawing.Point(104, 382);
            this.txtDocApMaterno.MaxLength = 32767;
            this.txtDocApMaterno.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDocApMaterno.Modified = false;
            this.txtDocApMaterno.Multiline = false;
            this.txtDocApMaterno.Name = "txtDocApMaterno";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocApMaterno.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDocApMaterno.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocApMaterno.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocApMaterno.OnIdleState = stateProperties16;
            this.txtDocApMaterno.Padding = new System.Windows.Forms.Padding(3);
            this.txtDocApMaterno.PasswordChar = '\0';
            this.txtDocApMaterno.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDocApMaterno.PlaceholderText = "Materno";
            this.txtDocApMaterno.ReadOnly = true;
            this.txtDocApMaterno.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDocApMaterno.SelectedText = "";
            this.txtDocApMaterno.SelectionLength = 0;
            this.txtDocApMaterno.SelectionStart = 0;
            this.txtDocApMaterno.ShortcutsEnabled = true;
            this.txtDocApMaterno.Size = new System.Drawing.Size(590, 37);
            this.txtDocApMaterno.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtDocApMaterno.TabIndex = 3;
            this.txtDocApMaterno.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDocApMaterno.TextMarginBottom = 0;
            this.txtDocApMaterno.TextMarginLeft = 3;
            this.txtDocApMaterno.TextMarginTop = 0;
            this.txtDocApMaterno.TextPlaceholder = "Materno";
            this.txtDocApMaterno.UseSystemPasswordChar = false;
            this.txtDocApMaterno.WordWrap = true;
            // 
            // txtDocApPaterno
            // 
            this.txtDocApPaterno.AcceptsReturn = false;
            this.txtDocApPaterno.AcceptsTab = false;
            this.txtDocApPaterno.AnimationSpeed = 200;
            this.txtDocApPaterno.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDocApPaterno.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDocApPaterno.BackColor = System.Drawing.Color.White;
            this.txtDocApPaterno.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDocApPaterno.BackgroundImage")));
            this.txtDocApPaterno.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDocApPaterno.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDocApPaterno.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDocApPaterno.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDocApPaterno.BorderRadius = 10;
            this.txtDocApPaterno.BorderThickness = 1;
            this.txtDocApPaterno.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDocApPaterno.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocApPaterno.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDocApPaterno.DefaultText = "";
            this.txtDocApPaterno.FillColor = System.Drawing.Color.White;
            this.txtDocApPaterno.HideSelection = true;
            this.txtDocApPaterno.IconLeft = null;
            this.txtDocApPaterno.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocApPaterno.IconPadding = 10;
            this.txtDocApPaterno.IconRight = null;
            this.txtDocApPaterno.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocApPaterno.Lines = new string[0];
            this.txtDocApPaterno.Location = new System.Drawing.Point(104, 309);
            this.txtDocApPaterno.MaxLength = 32767;
            this.txtDocApPaterno.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDocApPaterno.Modified = false;
            this.txtDocApPaterno.Multiline = false;
            this.txtDocApPaterno.Name = "txtDocApPaterno";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocApPaterno.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDocApPaterno.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocApPaterno.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocApPaterno.OnIdleState = stateProperties20;
            this.txtDocApPaterno.Padding = new System.Windows.Forms.Padding(3);
            this.txtDocApPaterno.PasswordChar = '\0';
            this.txtDocApPaterno.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDocApPaterno.PlaceholderText = "Paterno";
            this.txtDocApPaterno.ReadOnly = true;
            this.txtDocApPaterno.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDocApPaterno.SelectedText = "";
            this.txtDocApPaterno.SelectionLength = 0;
            this.txtDocApPaterno.SelectionStart = 0;
            this.txtDocApPaterno.ShortcutsEnabled = true;
            this.txtDocApPaterno.Size = new System.Drawing.Size(590, 37);
            this.txtDocApPaterno.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtDocApPaterno.TabIndex = 2;
            this.txtDocApPaterno.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDocApPaterno.TextMarginBottom = 0;
            this.txtDocApPaterno.TextMarginLeft = 3;
            this.txtDocApPaterno.TextMarginTop = 0;
            this.txtDocApPaterno.TextPlaceholder = "Paterno";
            this.txtDocApPaterno.UseSystemPasswordChar = false;
            this.txtDocApPaterno.WordWrap = true;
            // 
            // lblParEstApellido
            // 
            this.lblParEstApellido.AutoSize = true;
            this.lblParEstApellido.BackColor = System.Drawing.Color.Transparent;
            this.lblParEstApellido.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblParEstApellido.Enabled = false;
            this.lblParEstApellido.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblParEstApellido.ForeColor = System.Drawing.Color.DimGray;
            this.lblParEstApellido.Location = new System.Drawing.Point(41, 362);
            this.lblParEstApellido.Name = "lblParEstApellido";
            this.lblParEstApellido.Size = new System.Drawing.Size(120, 20);
            this.lblParEstApellido.TabIndex = 62;
            this.lblParEstApellido.Text = "Apellido Paterno";
            // 
            // label26
            // 
            this.label26.AutoSize = true;
            this.label26.BackColor = System.Drawing.Color.Transparent;
            this.label26.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label26.ForeColor = System.Drawing.Color.DimGray;
            this.label26.Location = new System.Drawing.Point(86, 667);
            this.label26.Name = "label26";
            this.label26.Size = new System.Drawing.Size(46, 20);
            this.label26.TabIndex = 75;
            this.label26.Text = "Email";
            // 
            // btnConfirmarDoc
            // 
            this.btnConfirmarDoc.AllowAnimations = true;
            this.btnConfirmarDoc.AllowMouseEffects = true;
            this.btnConfirmarDoc.AllowToggling = false;
            this.btnConfirmarDoc.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnConfirmarDoc.AnimationSpeed = 200;
            this.btnConfirmarDoc.AutoGenerateColors = false;
            this.btnConfirmarDoc.AutoRoundBorders = true;
            this.btnConfirmarDoc.AutoSizeLeftIcon = true;
            this.btnConfirmarDoc.AutoSizeRightIcon = true;
            this.btnConfirmarDoc.BackColor = System.Drawing.Color.Transparent;
            this.btnConfirmarDoc.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnConfirmarDoc.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnConfirmarDoc.BackgroundImage")));
            this.btnConfirmarDoc.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnConfirmarDoc.ButtonText = "Confirmar";
            this.btnConfirmarDoc.ButtonTextMarginLeft = 0;
            this.btnConfirmarDoc.ColorContrastOnClick = 45;
            this.btnConfirmarDoc.ColorContrastOnHover = 45;
            this.btnConfirmarDoc.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnConfirmarDoc.CustomizableEdges = borderEdges1;
            this.btnConfirmarDoc.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnConfirmarDoc.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnConfirmarDoc.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnConfirmarDoc.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnConfirmarDoc.Enabled = false;
            this.btnConfirmarDoc.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnConfirmarDoc.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnConfirmarDoc.ForeColor = System.Drawing.Color.White;
            this.btnConfirmarDoc.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnConfirmarDoc.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnConfirmarDoc.IconLeftPadding = new System.Windows.Forms.Padding(20, 3, 3, 3);
            this.btnConfirmarDoc.IconMarginLeft = 11;
            this.btnConfirmarDoc.IconPadding = 10;
            this.btnConfirmarDoc.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnConfirmarDoc.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnConfirmarDoc.IconRightPadding = new System.Windows.Forms.Padding(3);
            this.btnConfirmarDoc.IconSize = 25;
            this.btnConfirmarDoc.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnConfirmarDoc.IdleBorderRadius = 28;
            this.btnConfirmarDoc.IdleBorderThickness = 1;
            this.btnConfirmarDoc.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnConfirmarDoc.IdleIconLeftImage = global::CapaPresentacion.Properties.Resources.checked_26px;
            this.btnConfirmarDoc.IdleIconRightImage = null;
            this.btnConfirmarDoc.IndicateFocus = false;
            this.btnConfirmarDoc.Location = new System.Drawing.Point(526, 851);
            this.btnConfirmarDoc.Name = "btnConfirmarDoc";
            this.btnConfirmarDoc.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnConfirmarDoc.OnDisabledState.BorderRadius = 1;
            this.btnConfirmarDoc.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnConfirmarDoc.OnDisabledState.BorderThickness = 1;
            this.btnConfirmarDoc.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnConfirmarDoc.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnConfirmarDoc.OnDisabledState.IconLeftImage = null;
            this.btnConfirmarDoc.OnDisabledState.IconRightImage = null;
            this.btnConfirmarDoc.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnConfirmarDoc.onHoverState.BorderRadius = 1;
            this.btnConfirmarDoc.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnConfirmarDoc.onHoverState.BorderThickness = 1;
            this.btnConfirmarDoc.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnConfirmarDoc.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnConfirmarDoc.onHoverState.IconLeftImage = null;
            this.btnConfirmarDoc.onHoverState.IconRightImage = null;
            this.btnConfirmarDoc.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnConfirmarDoc.OnIdleState.BorderRadius = 1;
            this.btnConfirmarDoc.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnConfirmarDoc.OnIdleState.BorderThickness = 1;
            this.btnConfirmarDoc.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnConfirmarDoc.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnConfirmarDoc.OnIdleState.IconLeftImage = global::CapaPresentacion.Properties.Resources.checked_26px;
            this.btnConfirmarDoc.OnIdleState.IconRightImage = null;
            this.btnConfirmarDoc.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnConfirmarDoc.OnPressedState.BorderRadius = 1;
            this.btnConfirmarDoc.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnConfirmarDoc.OnPressedState.BorderThickness = 1;
            this.btnConfirmarDoc.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnConfirmarDoc.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnConfirmarDoc.OnPressedState.IconLeftImage = null;
            this.btnConfirmarDoc.OnPressedState.IconRightImage = null;
            this.btnConfirmarDoc.Size = new System.Drawing.Size(128, 30);
            this.btnConfirmarDoc.TabIndex = 66;
            this.btnConfirmarDoc.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnConfirmarDoc.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnConfirmarDoc.TextMarginLeft = 0;
            this.btnConfirmarDoc.TextPadding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.btnConfirmarDoc.UseDefaultRadiusAndThickness = true;
            this.btnConfirmarDoc.Click += new System.EventHandler(this.btnConfirmarDoc_Click);
            // 
            // btnImageDoc
            // 
            this.btnImageDoc.AllowAnimations = true;
            this.btnImageDoc.AllowMouseEffects = true;
            this.btnImageDoc.AllowToggling = false;
            this.btnImageDoc.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnImageDoc.AnimationSpeed = 200;
            this.btnImageDoc.AutoGenerateColors = false;
            this.btnImageDoc.AutoRoundBorders = true;
            this.btnImageDoc.AutoSizeLeftIcon = true;
            this.btnImageDoc.AutoSizeRightIcon = true;
            this.btnImageDoc.BackColor = System.Drawing.Color.Transparent;
            this.btnImageDoc.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnImageDoc.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnImageDoc.BackgroundImage")));
            this.btnImageDoc.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImageDoc.ButtonText = "Nueva Imagen";
            this.btnImageDoc.ButtonTextMarginLeft = 0;
            this.btnImageDoc.ColorContrastOnClick = 45;
            this.btnImageDoc.ColorContrastOnHover = 45;
            this.btnImageDoc.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnImageDoc.CustomizableEdges = borderEdges2;
            this.btnImageDoc.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnImageDoc.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnImageDoc.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnImageDoc.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnImageDoc.Enabled = false;
            this.btnImageDoc.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnImageDoc.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnImageDoc.ForeColor = System.Drawing.Color.White;
            this.btnImageDoc.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnImageDoc.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnImageDoc.IconLeftPadding = new System.Windows.Forms.Padding(15, 3, 3, 3);
            this.btnImageDoc.IconMarginLeft = 11;
            this.btnImageDoc.IconPadding = 10;
            this.btnImageDoc.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnImageDoc.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnImageDoc.IconRightPadding = new System.Windows.Forms.Padding(3);
            this.btnImageDoc.IconSize = 25;
            this.btnImageDoc.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnImageDoc.IdleBorderRadius = 28;
            this.btnImageDoc.IdleBorderThickness = 1;
            this.btnImageDoc.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnImageDoc.IdleIconLeftImage = global::CapaPresentacion.Properties.Resources.male_user_32px;
            this.btnImageDoc.IdleIconRightImage = null;
            this.btnImageDoc.IndicateFocus = false;
            this.btnImageDoc.Location = new System.Drawing.Point(252, 851);
            this.btnImageDoc.Name = "btnImageDoc";
            this.btnImageDoc.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnImageDoc.OnDisabledState.BorderRadius = 1;
            this.btnImageDoc.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImageDoc.OnDisabledState.BorderThickness = 1;
            this.btnImageDoc.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnImageDoc.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnImageDoc.OnDisabledState.IconLeftImage = null;
            this.btnImageDoc.OnDisabledState.IconRightImage = null;
            this.btnImageDoc.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnImageDoc.onHoverState.BorderRadius = 1;
            this.btnImageDoc.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImageDoc.onHoverState.BorderThickness = 1;
            this.btnImageDoc.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnImageDoc.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnImageDoc.onHoverState.IconLeftImage = null;
            this.btnImageDoc.onHoverState.IconRightImage = null;
            this.btnImageDoc.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnImageDoc.OnIdleState.BorderRadius = 1;
            this.btnImageDoc.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImageDoc.OnIdleState.BorderThickness = 1;
            this.btnImageDoc.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnImageDoc.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnImageDoc.OnIdleState.IconLeftImage = global::CapaPresentacion.Properties.Resources.male_user_32px;
            this.btnImageDoc.OnIdleState.IconRightImage = null;
            this.btnImageDoc.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnImageDoc.OnPressedState.BorderRadius = 1;
            this.btnImageDoc.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnImageDoc.OnPressedState.BorderThickness = 1;
            this.btnImageDoc.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnImageDoc.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnImageDoc.OnPressedState.IconLeftImage = null;
            this.btnImageDoc.OnPressedState.IconRightImage = null;
            this.btnImageDoc.Size = new System.Drawing.Size(131, 30);
            this.btnImageDoc.TabIndex = 68;
            this.btnImageDoc.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnImageDoc.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnImageDoc.TextMarginLeft = 0;
            this.btnImageDoc.TextPadding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.btnImageDoc.UseDefaultRadiusAndThickness = true;
            this.btnImageDoc.Click += new System.EventHandler(this.btnImageDoc_Click);
            // 
            // btnEditarDoc
            // 
            this.btnEditarDoc.AllowAnimations = true;
            this.btnEditarDoc.AllowMouseEffects = true;
            this.btnEditarDoc.AllowToggling = false;
            this.btnEditarDoc.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnEditarDoc.AnimationSpeed = 200;
            this.btnEditarDoc.AutoGenerateColors = false;
            this.btnEditarDoc.AutoRoundBorders = true;
            this.btnEditarDoc.AutoSizeLeftIcon = true;
            this.btnEditarDoc.AutoSizeRightIcon = true;
            this.btnEditarDoc.BackColor = System.Drawing.Color.Transparent;
            this.btnEditarDoc.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnEditarDoc.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEditarDoc.BackgroundImage")));
            this.btnEditarDoc.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditarDoc.ButtonText = "Editar";
            this.btnEditarDoc.ButtonTextMarginLeft = 0;
            this.btnEditarDoc.ColorContrastOnClick = 45;
            this.btnEditarDoc.ColorContrastOnHover = 45;
            this.btnEditarDoc.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnEditarDoc.CustomizableEdges = borderEdges3;
            this.btnEditarDoc.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEditarDoc.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEditarDoc.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEditarDoc.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEditarDoc.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnEditarDoc.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnEditarDoc.ForeColor = System.Drawing.Color.White;
            this.btnEditarDoc.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEditarDoc.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEditarDoc.IconLeftPadding = new System.Windows.Forms.Padding(30, 3, 3, 3);
            this.btnEditarDoc.IconMarginLeft = 11;
            this.btnEditarDoc.IconPadding = 10;
            this.btnEditarDoc.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEditarDoc.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEditarDoc.IconRightPadding = new System.Windows.Forms.Padding(3);
            this.btnEditarDoc.IconSize = 25;
            this.btnEditarDoc.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnEditarDoc.IdleBorderRadius = 28;
            this.btnEditarDoc.IdleBorderThickness = 1;
            this.btnEditarDoc.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnEditarDoc.IdleIconLeftImage = global::CapaPresentacion.Properties.Resources.edit_32px;
            this.btnEditarDoc.IdleIconRightImage = null;
            this.btnEditarDoc.IndicateFocus = false;
            this.btnEditarDoc.Location = new System.Drawing.Point(389, 851);
            this.btnEditarDoc.Name = "btnEditarDoc";
            this.btnEditarDoc.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEditarDoc.OnDisabledState.BorderRadius = 1;
            this.btnEditarDoc.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditarDoc.OnDisabledState.BorderThickness = 1;
            this.btnEditarDoc.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEditarDoc.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEditarDoc.OnDisabledState.IconLeftImage = null;
            this.btnEditarDoc.OnDisabledState.IconRightImage = null;
            this.btnEditarDoc.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEditarDoc.onHoverState.BorderRadius = 1;
            this.btnEditarDoc.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditarDoc.onHoverState.BorderThickness = 1;
            this.btnEditarDoc.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEditarDoc.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnEditarDoc.onHoverState.IconLeftImage = null;
            this.btnEditarDoc.onHoverState.IconRightImage = null;
            this.btnEditarDoc.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnEditarDoc.OnIdleState.BorderRadius = 1;
            this.btnEditarDoc.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditarDoc.OnIdleState.BorderThickness = 1;
            this.btnEditarDoc.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnEditarDoc.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnEditarDoc.OnIdleState.IconLeftImage = global::CapaPresentacion.Properties.Resources.edit_32px;
            this.btnEditarDoc.OnIdleState.IconRightImage = null;
            this.btnEditarDoc.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEditarDoc.OnPressedState.BorderRadius = 1;
            this.btnEditarDoc.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditarDoc.OnPressedState.BorderThickness = 1;
            this.btnEditarDoc.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEditarDoc.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnEditarDoc.OnPressedState.IconLeftImage = null;
            this.btnEditarDoc.OnPressedState.IconRightImage = null;
            this.btnEditarDoc.Size = new System.Drawing.Size(131, 30);
            this.btnEditarDoc.TabIndex = 69;
            this.btnEditarDoc.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEditarDoc.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEditarDoc.TextMarginLeft = 0;
            this.btnEditarDoc.TextPadding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.btnEditarDoc.UseDefaultRadiusAndThickness = true;
            this.btnEditarDoc.Click += new System.EventHandler(this.btnEditarDoc_Click);
            // 
            // txtDocEmail
            // 
            this.txtDocEmail.AcceptsReturn = false;
            this.txtDocEmail.AcceptsTab = false;
            this.txtDocEmail.AnimationSpeed = 200;
            this.txtDocEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDocEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDocEmail.BackColor = System.Drawing.Color.White;
            this.txtDocEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDocEmail.BackgroundImage")));
            this.txtDocEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDocEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDocEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDocEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDocEmail.BorderRadius = 10;
            this.txtDocEmail.BorderThickness = 1;
            this.txtDocEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDocEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDocEmail.DefaultText = "";
            this.txtDocEmail.FillColor = System.Drawing.Color.White;
            this.txtDocEmail.HideSelection = true;
            this.txtDocEmail.IconLeft = null;
            this.txtDocEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocEmail.IconPadding = 10;
            this.txtDocEmail.IconRight = null;
            this.txtDocEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocEmail.Lines = new string[0];
            this.txtDocEmail.Location = new System.Drawing.Point(87, 690);
            this.txtDocEmail.MaxLength = 200;
            this.txtDocEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDocEmail.Modified = false;
            this.txtDocEmail.Multiline = false;
            this.txtDocEmail.Name = "txtDocEmail";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocEmail.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDocEmail.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocEmail.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocEmail.OnIdleState = stateProperties24;
            this.txtDocEmail.Padding = new System.Windows.Forms.Padding(3);
            this.txtDocEmail.PasswordChar = '\0';
            this.txtDocEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDocEmail.PlaceholderText = "Email";
            this.txtDocEmail.ReadOnly = true;
            this.txtDocEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDocEmail.SelectedText = "";
            this.txtDocEmail.SelectionLength = 0;
            this.txtDocEmail.SelectionStart = 0;
            this.txtDocEmail.ShortcutsEnabled = true;
            this.txtDocEmail.Size = new System.Drawing.Size(590, 37);
            this.txtDocEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtDocEmail.TabIndex = 74;
            this.txtDocEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDocEmail.TextMarginBottom = 0;
            this.txtDocEmail.TextMarginLeft = 3;
            this.txtDocEmail.TextMarginTop = 0;
            this.txtDocEmail.TextPlaceholder = "Email";
            this.txtDocEmail.UseSystemPasswordChar = false;
            this.txtDocEmail.WordWrap = true;
            // 
            // gbDoc
            // 
            this.gbDoc.BorderColor = System.Drawing.Color.LightGray;
            this.gbDoc.BorderRadius = 1;
            this.gbDoc.BorderThickness = 1;
            this.gbDoc.Controls.Add(this.bunifuLabel1);
            this.gbDoc.Controls.Add(this.rdbDocMasculino);
            this.gbDoc.Controls.Add(this.lblMasculino);
            this.gbDoc.Controls.Add(this.lblFemenino);
            this.gbDoc.Controls.Add(this.rdbDocFemenino);
            this.gbDoc.Enabled = false;
            this.gbDoc.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.gbDoc.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.gbDoc.LabelIndent = 10;
            this.gbDoc.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.gbDoc.Location = new System.Drawing.Point(90, 505);
            this.gbDoc.Name = "gbDoc";
            this.gbDoc.Size = new System.Drawing.Size(196, 58);
            this.gbDoc.TabIndex = 73;
            this.gbDoc.TabStop = false;
            this.gbDoc.Text = "Sexo";
            // 
            // rdbDocMasculino
            // 
            this.rdbDocMasculino.AllowBindingControlLocation = true;
            this.rdbDocMasculino.BackColor = System.Drawing.Color.Transparent;
            this.rdbDocMasculino.BindingControl = this.lblMasculino;
            this.rdbDocMasculino.BindingControlPosition = Bunifu.UI.WinForms.BunifuRadioButton.BindingControlPositions.Right;
            this.rdbDocMasculino.BorderThickness = 1;
            this.rdbDocMasculino.Checked = false;
            this.rdbDocMasculino.Enabled = false;
            this.rdbDocMasculino.Location = new System.Drawing.Point(17, 22);
            this.rdbDocMasculino.Name = "rdbDocMasculino";
            this.rdbDocMasculino.OutlineColor = System.Drawing.Color.DodgerBlue;
            this.rdbDocMasculino.OutlineColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.rdbDocMasculino.OutlineColorUnchecked = System.Drawing.Color.DarkGray;
            this.rdbDocMasculino.RadioColor = System.Drawing.Color.DodgerBlue;
            this.rdbDocMasculino.RadioColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.rdbDocMasculino.Size = new System.Drawing.Size(21, 21);
            this.rdbDocMasculino.TabIndex = 32;
            this.rdbDocMasculino.Text = null;
            // 
            // lblMasculino
            // 
            this.lblMasculino.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
            this.lblMasculino.AllowParentOverrides = false;
            this.lblMasculino.AutoEllipsis = false;
            this.lblMasculino.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblMasculino.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblMasculino.Enabled = false;
            this.lblMasculino.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblMasculino.Location = new System.Drawing.Point(41, 26);
            this.lblMasculino.Name = "lblMasculino";
            this.lblMasculino.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblMasculino.Size = new System.Drawing.Size(55, 15);
            this.lblMasculino.TabIndex = 28;
            this.lblMasculino.Text = "Masculino";
            this.lblMasculino.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblMasculino.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblFemenino
            // 
            this.lblFemenino.AllowParentOverrides = false;
            this.lblFemenino.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.lblFemenino.AutoEllipsis = false;
            this.lblFemenino.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblFemenino.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblFemenino.Enabled = false;
            this.lblFemenino.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblFemenino.Location = new System.Drawing.Point(41, 26);
            this.lblFemenino.Name = "lblFemenino";
            this.lblFemenino.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblFemenino.Size = new System.Drawing.Size(53, 15);
            this.lblFemenino.TabIndex = 29;
            this.lblFemenino.Text = "Femenino";
            this.lblFemenino.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblFemenino.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // rdbDocFemenino
            // 
            this.rdbDocFemenino.AllowBindingControlLocation = true;
            this.rdbDocFemenino.BackColor = System.Drawing.Color.Transparent;
            this.rdbDocFemenino.BindingControl = this.lblFemenino;
            this.rdbDocFemenino.BindingControlPosition = Bunifu.UI.WinForms.BunifuRadioButton.BindingControlPositions.Right;
            this.rdbDocFemenino.BorderThickness = 1;
            this.rdbDocFemenino.Checked = true;
            this.rdbDocFemenino.Enabled = false;
            this.rdbDocFemenino.Location = new System.Drawing.Point(102, 22);
            this.rdbDocFemenino.Name = "rdbDocFemenino";
            this.rdbDocFemenino.OutlineColor = System.Drawing.Color.DodgerBlue;
            this.rdbDocFemenino.OutlineColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.rdbDocFemenino.OutlineColorUnchecked = System.Drawing.Color.DarkGray;
            this.rdbDocFemenino.RadioColor = System.Drawing.Color.DodgerBlue;
            this.rdbDocFemenino.RadioColorTabFocused = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.rdbDocFemenino.Size = new System.Drawing.Size(21, 21);
            this.rdbDocFemenino.TabIndex = 33;
            this.rdbDocFemenino.Text = null;
            // 
            // lblParEstDireccion
            // 
            this.lblParEstDireccion.AutoSize = true;
            this.lblParEstDireccion.BackColor = System.Drawing.Color.Transparent;
            this.lblParEstDireccion.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblParEstDireccion.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblParEstDireccion.ForeColor = System.Drawing.Color.DimGray;
            this.lblParEstDireccion.Location = new System.Drawing.Point(41, 362);
            this.lblParEstDireccion.Name = "lblParEstDireccion";
            this.lblParEstDireccion.Size = new System.Drawing.Size(72, 20);
            this.lblParEstDireccion.TabIndex = 72;
            this.lblParEstDireccion.Text = "Direccion";
            // 
            // dpkDocFecNacimiento
            // 
            this.dpkDocFecNacimiento.BackColor = System.Drawing.Color.Transparent;
            this.dpkDocFecNacimiento.BorderRadius = 10;
            this.dpkDocFecNacimiento.Color = System.Drawing.Color.Silver;
            this.dpkDocFecNacimiento.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dpkDocFecNacimiento.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dpkDocFecNacimiento.DisabledColor = System.Drawing.Color.Gray;
            this.dpkDocFecNacimiento.DisplayWeekNumbers = false;
            this.dpkDocFecNacimiento.DPHeight = 0;
            this.dpkDocFecNacimiento.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dpkDocFecNacimiento.Enabled = false;
            this.dpkDocFecNacimiento.FillDatePicker = false;
            this.dpkDocFecNacimiento.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.dpkDocFecNacimiento.ForeColor = System.Drawing.Color.Black;
            this.dpkDocFecNacimiento.Icon = ((System.Drawing.Image)(resources.GetObject("dpkDocFecNacimiento.Icon")));
            this.dpkDocFecNacimiento.IconColor = System.Drawing.Color.Gray;
            this.dpkDocFecNacimiento.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dpkDocFecNacimiento.LeftTextMargin = 5;
            this.dpkDocFecNacimiento.Location = new System.Drawing.Point(330, 531);
            this.dpkDocFecNacimiento.MinimumSize = new System.Drawing.Size(4, 32);
            this.dpkDocFecNacimiento.Name = "dpkDocFecNacimiento";
            this.dpkDocFecNacimiento.Size = new System.Drawing.Size(347, 32);
            this.dpkDocFecNacimiento.TabIndex = 67;
            this.dpkDocFecNacimiento.Value = new System.DateTime(2021, 6, 23, 0, 0, 0, 0);
            // 
            // txtDocDireccion
            // 
            this.txtDocDireccion.AcceptsReturn = false;
            this.txtDocDireccion.AcceptsTab = false;
            this.txtDocDireccion.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtDocDireccion.AnimationSpeed = 200;
            this.txtDocDireccion.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDocDireccion.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDocDireccion.BackColor = System.Drawing.Color.White;
            this.txtDocDireccion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDocDireccion.BackgroundImage")));
            this.txtDocDireccion.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDocDireccion.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDocDireccion.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDocDireccion.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDocDireccion.BorderRadius = 10;
            this.txtDocDireccion.BorderThickness = 1;
            this.txtDocDireccion.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDocDireccion.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocDireccion.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDocDireccion.DefaultText = "";
            this.txtDocDireccion.FillColor = System.Drawing.Color.White;
            this.txtDocDireccion.HideSelection = true;
            this.txtDocDireccion.IconLeft = null;
            this.txtDocDireccion.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocDireccion.IconPadding = 10;
            this.txtDocDireccion.IconRight = null;
            this.txtDocDireccion.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocDireccion.Lines = new string[0];
            this.txtDocDireccion.Location = new System.Drawing.Point(87, 610);
            this.txtDocDireccion.MaxLength = 500;
            this.txtDocDireccion.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDocDireccion.Modified = false;
            this.txtDocDireccion.Multiline = false;
            this.txtDocDireccion.Name = "txtDocDireccion";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocDireccion.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDocDireccion.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocDireccion.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocDireccion.OnIdleState = stateProperties28;
            this.txtDocDireccion.Padding = new System.Windows.Forms.Padding(3);
            this.txtDocDireccion.PasswordChar = '\0';
            this.txtDocDireccion.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDocDireccion.PlaceholderText = "Direccion";
            this.txtDocDireccion.ReadOnly = true;
            this.txtDocDireccion.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDocDireccion.SelectedText = "";
            this.txtDocDireccion.SelectionLength = 0;
            this.txtDocDireccion.SelectionStart = 0;
            this.txtDocDireccion.ShortcutsEnabled = true;
            this.txtDocDireccion.Size = new System.Drawing.Size(276, 37);
            this.txtDocDireccion.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtDocDireccion.TabIndex = 71;
            this.txtDocDireccion.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDocDireccion.TextMarginBottom = 0;
            this.txtDocDireccion.TextMarginLeft = 3;
            this.txtDocDireccion.TextMarginTop = 0;
            this.txtDocDireccion.TextPlaceholder = "Direccion";
            this.txtDocDireccion.UseSystemPasswordChar = false;
            this.txtDocDireccion.WordWrap = true;
            // 
            // lblParEstFechaNac
            // 
            this.lblParEstFechaNac.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.lblParEstFechaNac.AutoSize = true;
            this.lblParEstFechaNac.BackColor = System.Drawing.Color.Transparent;
            this.lblParEstFechaNac.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblParEstFechaNac.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblParEstFechaNac.ForeColor = System.Drawing.Color.DimGray;
            this.lblParEstFechaNac.Location = new System.Drawing.Point(41, 362);
            this.lblParEstFechaNac.Name = "lblParEstFechaNac";
            this.lblParEstFechaNac.Size = new System.Drawing.Size(149, 20);
            this.lblParEstFechaNac.TabIndex = 70;
            this.lblParEstFechaNac.Text = "Fecha de Nacimiento";
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 3;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Location = new System.Drawing.Point(-6, 887);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(729, 10);
            this.bunifuPanel2.TabIndex = 76;
            this.bunifuPanel2.Click += new System.EventHandler(this.bunifuPanel2_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.DimGray;
            this.label1.Location = new System.Drawing.Point(83, 748);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(93, 20);
            this.label1.TabIndex = 78;
            this.label1.Text = "Especialidad";
            // 
            // txtDocEsp
            // 
            this.txtDocEsp.AcceptsReturn = false;
            this.txtDocEsp.AcceptsTab = false;
            this.txtDocEsp.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtDocEsp.AnimationSpeed = 200;
            this.txtDocEsp.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDocEsp.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDocEsp.BackColor = System.Drawing.Color.White;
            this.txtDocEsp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDocEsp.BackgroundImage")));
            this.txtDocEsp.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDocEsp.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDocEsp.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDocEsp.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDocEsp.BorderRadius = 10;
            this.txtDocEsp.BorderThickness = 1;
            this.txtDocEsp.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDocEsp.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocEsp.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDocEsp.DefaultText = "";
            this.txtDocEsp.FillColor = System.Drawing.Color.White;
            this.txtDocEsp.HideSelection = true;
            this.txtDocEsp.IconLeft = null;
            this.txtDocEsp.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocEsp.IconPadding = 10;
            this.txtDocEsp.IconRight = null;
            this.txtDocEsp.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDocEsp.Lines = new string[0];
            this.txtDocEsp.Location = new System.Drawing.Point(87, 771);
            this.txtDocEsp.MaxLength = 500;
            this.txtDocEsp.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDocEsp.Modified = false;
            this.txtDocEsp.Multiline = false;
            this.txtDocEsp.Name = "txtDocEsp";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocEsp.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDocEsp.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocEsp.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDocEsp.OnIdleState = stateProperties32;
            this.txtDocEsp.Padding = new System.Windows.Forms.Padding(3);
            this.txtDocEsp.PasswordChar = '\0';
            this.txtDocEsp.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDocEsp.PlaceholderText = "Especialidad";
            this.txtDocEsp.ReadOnly = true;
            this.txtDocEsp.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDocEsp.SelectedText = "";
            this.txtDocEsp.SelectionLength = 0;
            this.txtDocEsp.SelectionStart = 0;
            this.txtDocEsp.ShortcutsEnabled = true;
            this.txtDocEsp.Size = new System.Drawing.Size(276, 37);
            this.txtDocEsp.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtDocEsp.TabIndex = 77;
            this.txtDocEsp.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDocEsp.TextMarginBottom = 0;
            this.txtDocEsp.TextMarginLeft = 3;
            this.txtDocEsp.TextMarginTop = 0;
            this.txtDocEsp.TextPlaceholder = "Especialidad";
            this.txtDocEsp.UseSystemPasswordChar = false;
            this.txtDocEsp.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Enabled = false;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel1.Location = new System.Drawing.Point(129, 26);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(53, 15);
            this.bunifuLabel1.TabIndex = 79;
            this.bunifuLabel1.Text = "Femenino";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // DocenteDetalle
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoScroll = true;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(784, 561);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.txtDocEsp);
            this.Controls.Add(this.bunifuPanel2);
            this.Controls.Add(this.label26);
            this.Controls.Add(this.btnConfirmarDoc);
            this.Controls.Add(this.btnImageDoc);
            this.Controls.Add(this.btnEditarDoc);
            this.Controls.Add(this.txtDocEmail);
            this.Controls.Add(this.gbDoc);
            this.Controls.Add(this.lblParEstDireccion);
            this.Controls.Add(this.dpkDocFecNacimiento);
            this.Controls.Add(this.txtDocDireccion);
            this.Controls.Add(this.lblParEstFechaNac);
            this.Controls.Add(this.imgDocPerfil);
            this.Controls.Add(this.label27);
            this.Controls.Add(this.txtDocTelefono);
            this.Controls.Add(this.txtDocNombre);
            this.Controls.Add(this.lblParEstNombre);
            this.Controls.Add(this.txtDocDni);
            this.Controls.Add(this.label25);
            this.Controls.Add(this.lblParamEstDni);
            this.Controls.Add(this.txtDocApMaterno);
            this.Controls.Add(this.txtDocApPaterno);
            this.Controls.Add(this.lblParEstApellido);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.Name = "DocenteDetalle";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Detalle del Docente";
            ((System.ComponentModel.ISupportInitialize)(this.imgDocPerfil)).EndInit();
            this.gbDoc.ResumeLayout(false);
            this.gbDoc.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPictureBox imgDocPerfil;
        private System.Windows.Forms.Label label27;
        private Bunifu.UI.WinForms.BunifuTextBox txtDocTelefono;
        public Bunifu.UI.WinForms.BunifuTextBox txtDocNombre;
        private System.Windows.Forms.Label lblParEstNombre;
        private Bunifu.UI.WinForms.BunifuTextBox txtDocDni;
        private System.Windows.Forms.Label label25;
        private System.Windows.Forms.Label lblParamEstDni;
        private Bunifu.UI.WinForms.BunifuTextBox txtDocApMaterno;
        private Bunifu.UI.WinForms.BunifuTextBox txtDocApPaterno;
        private System.Windows.Forms.Label lblParEstApellido;
        private System.Windows.Forms.Label label26;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnConfirmarDoc;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnImageDoc;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnEditarDoc;
        private Bunifu.UI.WinForms.BunifuTextBox txtDocEmail;
        private Bunifu.UI.WinForms.BunifuGroupBox gbDoc;
        private Bunifu.UI.WinForms.BunifuRadioButton rdbDocMasculino;
        private Bunifu.UI.WinForms.BunifuLabel lblMasculino;
        private Bunifu.UI.WinForms.BunifuLabel lblFemenino;
        private Bunifu.UI.WinForms.BunifuRadioButton rdbDocFemenino;
        private System.Windows.Forms.Label lblParEstDireccion;
        private Bunifu.UI.WinForms.BunifuDatePicker dpkDocFecNacimiento;
        private Bunifu.UI.WinForms.BunifuTextBox txtDocDireccion;
        private System.Windows.Forms.Label lblParEstFechaNac;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox txtDocEsp;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
    }
}